### ISSUE TITLE
CIKM2021-SimpleX

### ISSUE THREAD

**Issue by junkangwu** [openbenchmark/Open-Match-Benchmark#7]
May I ask you about the hyper parameters of the amazon-book and gowalla?
 Thanks a lot in advance!

**Comment by zhujiem** [comment]
+ MF-CCL for amazonbooks_x0
> [Metrics] Recall(k=20): 0.055937 - Recall(k=50): 0.096077 - NDCG(k=20): 0.044708 - NDCG(k=50): 0.059571 - HitRate(k=20): 0.294288 - HitRate(k=50): 0.442676

```
base_config: ../config/
base_expid: MF_base
dataset_id: amazonbooks_x0

dataset_config:
    amazonbooks_x0:
        data_root: ../data/AmazonBooks/
        data_format: csv
        train_data: ../data/AmazonBooks/amazonbooks_x0/train.csv
        valid_data: ../data/AmazonBooks/amazonbooks_x0/test.csv
        item_corpus: ../data/AmazonBooks/amazonbooks_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item'}
        label_col: {name: label, dtype: float}

tuner_space:
    model_root: './AmazonBooks/MF_CCL_amazonbooks_x0/'
    learning_rate: 1.e-3
    embedding_dim: 64
    embedding_dropout: 0
    num_negs: 1500
    regularizer: 1.e-5
    similarity_score: cosine
    loss: CosineContrastiveLoss
    negative_weight: 250
    margin: 0.2
    batch_size: 512
    seed: 2019
    monitor: Recall(k=20)
```
+ SimpleX for amazonbooks_x0
> [Metrics] Recall(k=20): 0.058341 - Recall(k=50): 0.100549 - NDCG(k=20): 0.046792 - NDCG(k=50): 0.062420 - HitRate(k=20): 0.303007 - HitRate(k=50): 0.455727

```
base_config: ../config/
base_expid: SimpleX_base
dataset_id: amazonbooks_x0

dataset_config:
    amazonbooks_x0:
        data_root: ../data/AmazonBooks/
        data_format: csv
        train_data: ../data/AmazonBooks/amazonbooks_x0/train.csv
        valid_data: ../data/AmazonBooks/amazonbooks_x0/test.csv
        item_corpus: ../data/AmazonBooks/amazonbooks_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'user_history', 'active': True, 'dtype': str, 'type': 'sequence', 'source': 'user', 'splitter': '^',
               'max_len': 500, 'padding': 'pre', 'embedding_callback': null}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item', 'share_embedding': 'user_history'}
        label_col: {name: label, dtype: float}

tuner_space:
    model_root: './AmazonBooks/SimpleX_amazonbooks_x0/'
    learning_rate: 1.e-3
    embedding_dim: 64
    num_negs: 1000
    embedding_regularizer: 1.e-6
    similarity_score: cosine
    loss: CosineContrastiveLoss
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    aggregator: mean
    gamma: 0.5
    net_dropout: 0.1
    attention_dropout: 0
    negative_weight: 300
    margin: 0.4
    ignore_pos_items: False
    sampling_num_process: 1
    fix_sampling_seeds: False
    enable_bias: False
    batch_size: 1024
    seed: 2019
    monitor: {"Recall(k=20)": 1, "NDCG(k=20)": 1}
```

+ MF-CCL for gowalla_x0
> [Metrics] Recall(k=20): 0.183730 - Recall(k=50): 0.287096 - NDCG(k=20): 0.149257 - NDCG(k=50): 0.181573 - HitRate(k=20): 0.584031 - HitRate(k=50): 0.724262

```
base_config: ../config/
base_expid: MF_base
dataset_id: gowalla_x0

dataset_config:
    gowalla_x0:
        data_root: ../data/Gowalla/
        data_format: csv
        train_data: ../data/Gowalla/gowalla_x0/train.csv
        valid_data: ../data/Gowalla/gowalla_x0/test.csv
        item_corpus: ../data/Gowalla/gowalla_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item'}
        label_col: {name: label, dtype: float}


tuner_space:
    model_root: './Gowalla/MF_CCL_gowalla_x0/'
    learning_rate: 1.e-4
    embedding_dim: 64
    embedding_dropout: 0.1
    num_negs: 800
    regularizer: 1.e-8
    similarity_score: cosine
    loss: CosineContrastiveLoss
    negative_weight: 150
    margin: 0.9
    batch_size: 256
    seed: 2019
    monitor: Recall(k=20)
```

+ SimpleX for gowalla_x0
> [Metrics] Recall(k=20): 0.187213 - Recall(k=50): 0.287394 - NDCG(k=20): 0.155688 - NDCG(k=50): 0.186816 - HitRate(k=20): 0.592705 - HitRate(k=50): 0.727242

```
base_config: ../config/
base_expid: SimpleX_base
dataset_id: gowalla_x0

dataset_config:
    gowalla_x0:
        data_root: ../data/Gowalla/
        data_format: csv
        train_data: ../data/Gowalla/gowalla_x0/train.csv
        valid_data: ../data/Gowalla/gowalla_x0/test.csv
        item_corpus: ../data/Gowalla/gowalla_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'user_history', 'active': True, 'dtype': str, 'type': 'sequence', 'source': 'user', 'splitter': '^',
               'padding': 'pre', 'embedding_callback': null}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item'}
        label_col: {name: label, dtype: float}

tuner_space:
    model_root: './Gowalla/SimpleX_gowalla_x0/'
    learning_rate: 1.e-4
    embedding_dim: 64
    num_negs: 2000
    embedding_regularizer: 1.e-7
    similarity_score: cosine
    loss: CosineContrastiveLoss
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    aggregator: cross_attention
    gamma: [0.8, 0.9]
    net_dropout: 0.1
    attention_dropout: 0
    negative_weight: 250
    margin: 0.9
    ignore_pos_items: False
    sampling_num_process: 1
    fix_sampling_seeds: False
    enable_bias: False
    batch_size: 256
    seed: 2019
    monitor: "NDCG(k=20)"
```
